
#ifndef __airspeed__idl__
#define __airspeed__idl__





struct airspeed
{
    unsigned long long timestamp_;
    float indicated_airspeed_m_s_;
    float true_airspeed_m_s_;
    float air_temperature_celsius_;
    float confidence_;

}; // struct airspeed

#pragma keylist airspeed

#endif  // __airspeed__idl__
