
#ifndef __camera_capture__idl__
#define __camera_capture__idl__




typedef float camera_capture__float_array_4[4];

struct camera_capture
{
    unsigned long long timestamp_;
    unsigned long long timestamp_utc_;
    unsigned long seq_;
    double lat_;
    double lon_;
    float alt_;
    float ground_distance_;
    camera_capture__float_array_4 q;
    octet result_;

}; // struct camera_capture

#pragma keylist camera_capture

#endif  // __camera_capture__idl__
