
#ifndef __collision_report__idl__
#define __collision_report__idl__





struct collision_report
{
    unsigned long long timestamp_;
    octet src_;
    unsigned long id_;
    octet action_;
    octet threat_level_;
    float time_to_minimum_delta_;
    float altitude_minimum_delta_;
    float horizontal_minimum_delta_;

}; // struct collision_report

#pragma keylist collision_report

#endif  // __collision_report__idl__
