
#ifndef __cpuload__idl__
#define __cpuload__idl__





struct cpuload
{
    unsigned long long timestamp_;
    float load_;
    float ram_usage_;

}; // struct cpuload

#pragma keylist cpuload

#endif  // __cpuload__idl__
