
#ifndef __distance_sensor__idl__
#define __distance_sensor__idl__



const octet distance_sensor__MAV_DISTANCE_SENSOR_LASER = 0;
const octet distance_sensor__MAV_DISTANCE_SENSOR_ULTRASOUND = 1;
const octet distance_sensor__MAV_DISTANCE_SENSOR_INFRARED = 2;
const octet distance_sensor__MAV_DISTANCE_SENSOR_RADAR = 3;
const octet distance_sensor__ROTATION_YAW_0 = 0;
const octet distance_sensor__ROTATION_YAW_45 = 1;
const octet distance_sensor__ROTATION_YAW_90 = 2;
const octet distance_sensor__ROTATION_YAW_135 = 3;
const octet distance_sensor__ROTATION_YAW_180 = 4;
const octet distance_sensor__ROTATION_YAW_225 = 5;
const octet distance_sensor__ROTATION_YAW_270 = 6;
const octet distance_sensor__ROTATION_YAW_315 = 7;
const octet distance_sensor__ROTATION_FORWARD_FACING = 0;
const octet distance_sensor__ROTATION_RIGHT_FACING = 2;
const octet distance_sensor__ROTATION_BACKWARD_FACING = 4;
const octet distance_sensor__ROTATION_LEFT_FACING = 6;
const octet distance_sensor__ROTATION_UPWARD_FACING = 24;
const octet distance_sensor__ROTATION_DOWNWARD_FACING = 25;
const octet distance_sensor__ROTATION_CUSTOM = 100;

typedef float distance_sensor__float_array_4[4];

struct distance_sensor
{
    unsigned long long timestamp_;
    float min_distance_;
    float max_distance_;
    float current_distance_;
    float variance_;
    octet signal_quality_;
    octet type_;
    octet id_;
    float h_fov_;
    float v_fov_;
    distance_sensor__float_array_4 q;
    octet orientation_;

}; // struct distance_sensor

#pragma keylist distance_sensor

#endif  // __distance_sensor__idl__
