
#ifndef __estimator_status__idl__
#define __estimator_status__idl__



const octet estimator_status__GPS_CHECK_FAIL_GPS_FIX = 0;
const octet estimator_status__GPS_CHECK_FAIL_MIN_SAT_COUNT = 1;
const octet estimator_status__GPS_CHECK_FAIL_MIN_PDOP = 2;
const octet estimator_status__GPS_CHECK_FAIL_MAX_HORZ_ERR = 3;
const octet estimator_status__GPS_CHECK_FAIL_MAX_VERT_ERR = 4;
const octet estimator_status__GPS_CHECK_FAIL_MAX_SPD_ERR = 5;
const octet estimator_status__GPS_CHECK_FAIL_MAX_HORZ_DRIFT = 6;
const octet estimator_status__GPS_CHECK_FAIL_MAX_VERT_DRIFT = 7;
const octet estimator_status__GPS_CHECK_FAIL_MAX_HORZ_SPD_ERR = 8;
const octet estimator_status__GPS_CHECK_FAIL_MAX_VERT_SPD_ERR = 9;
const octet estimator_status__CS_TILT_ALIGN = 0;
const octet estimator_status__CS_YAW_ALIGN = 1;
const octet estimator_status__CS_GPS = 2;
const octet estimator_status__CS_OPT_FLOW = 3;
const octet estimator_status__CS_MAG_HDG = 4;
const octet estimator_status__CS_MAG_3D = 5;
const octet estimator_status__CS_MAG_DEC = 6;
const octet estimator_status__CS_IN_AIR = 7;
const octet estimator_status__CS_WIND = 8;
const octet estimator_status__CS_BARO_HGT = 9;
const octet estimator_status__CS_RNG_HGT = 10;
const octet estimator_status__CS_GPS_HGT = 11;
const octet estimator_status__CS_EV_POS = 12;
const octet estimator_status__CS_EV_YAW = 13;
const octet estimator_status__CS_EV_HGT = 14;
const octet estimator_status__CS_BETA = 15;
const octet estimator_status__CS_MAG_FIELD = 16;
const octet estimator_status__CS_FIXED_WING = 17;
const octet estimator_status__CS_MAG_FAULT = 18;
const octet estimator_status__CS_ASPD = 19;
const octet estimator_status__CS_GND_EFFECT = 20;
const octet estimator_status__CS_RNG_STUCK = 21;
const octet estimator_status__CS_GPS_YAW = 22;
const octet estimator_status__CS_MAG_ALIGNED = 23;

typedef float estimator_status__float_array_24[24];
typedef float estimator_status__float_array_3[3];

struct estimator_status
{
    unsigned long long timestamp_;
    estimator_status__float_array_24 states;
    octet n_states_;
    estimator_status__float_array_3 vibe;
    estimator_status__float_array_24 covariances;
    estimator_status__float_array_3 output_tracking_error;
    unsigned short gps_check_fail_flags_;
    unsigned long control_mode_flags_;
    unsigned short filter_fault_flags_;
    float pos_horiz_accuracy_;
    float pos_vert_accuracy_;
    unsigned short innovation_check_flags_;
    float mag_test_ratio_;
    float vel_test_ratio_;
    float pos_test_ratio_;
    float hgt_test_ratio_;
    float tas_test_ratio_;
    float hagl_test_ratio_;
    float beta_test_ratio_;
    unsigned short solution_status_flags_;
    float time_slip_;
    boolean pre_flt_fail_innov_heading_;
    boolean pre_flt_fail_innov_vel_horiz_;
    boolean pre_flt_fail_innov_vel_vert_;
    boolean pre_flt_fail_innov_height_;
    boolean pre_flt_fail_mag_field_disturbed_;
    octet health_flags_;
    octet timeout_flags_;

}; // struct estimator_status

#pragma keylist estimator_status

#endif  // __estimator_status__idl__
