
#ifndef __home_position__idl__
#define __home_position__idl__





struct home_position
{
    unsigned long long timestamp_;
    double lat_;
    double lon_;
    float alt_;
    float x_;
    float y_;
    float z_;
    float yaw_;
    boolean valid_alt_;
    boolean valid_hpos_;
    boolean manual_home_;

}; // struct home_position

#pragma keylist home_position

#endif  // __home_position__idl__
