
#ifndef __input_rc__idl__
#define __input_rc__idl__



const octet input_rc__RC_INPUT_SOURCE_UNKNOWN = 0;
const octet input_rc__RC_INPUT_SOURCE_PX4FMU_PPM = 1;
const octet input_rc__RC_INPUT_SOURCE_PX4IO_PPM = 2;
const octet input_rc__RC_INPUT_SOURCE_PX4IO_SPEKTRUM = 3;
const octet input_rc__RC_INPUT_SOURCE_PX4IO_SBUS = 4;
const octet input_rc__RC_INPUT_SOURCE_PX4IO_ST24 = 5;
const octet input_rc__RC_INPUT_SOURCE_MAVLINK = 6;
const octet input_rc__RC_INPUT_SOURCE_QURT = 7;
const octet input_rc__RC_INPUT_SOURCE_PX4FMU_SPEKTRUM = 8;
const octet input_rc__RC_INPUT_SOURCE_PX4FMU_SBUS = 9;
const octet input_rc__RC_INPUT_SOURCE_PX4FMU_ST24 = 10;
const octet input_rc__RC_INPUT_SOURCE_PX4FMU_SUMD = 11;
const octet input_rc__RC_INPUT_SOURCE_PX4FMU_DSM = 12;
const octet input_rc__RC_INPUT_SOURCE_PX4IO_SUMD = 13;
const octet input_rc__RC_INPUT_SOURCE_PX4FMU_CRSF = 14;
const octet input_rc__RC_INPUT_SOURCE_PX4FMU_GHST = 15;
const octet input_rc__RC_INPUT_MAX_CHANNELS = 18;

typedef unsigned short input_rc__unsigned_short_array_18[18];

struct input_rc
{
    unsigned long long timestamp_;
    unsigned long long timestamp_last_signal_;
    octet channel_count_;
    long rssi_;
    boolean rc_failsafe_;
    boolean rc_lost_;
    unsigned short rc_lost_frame_count_;
    unsigned short rc_total_frame_count_;
    unsigned short rc_ppm_frame_length_;
    octet input_source_;
    input_rc__unsigned_short_array_18 values;

}; // struct input_rc

#pragma keylist input_rc

#endif  // __input_rc__idl__
