
#ifndef __obstacle_distance__idl__
#define __obstacle_distance__idl__



const octet obstacle_distance__MAV_FRAME_GLOBAL = 0;
const octet obstacle_distance__MAV_FRAME_LOCAL_NED = 1;
const octet obstacle_distance__MAV_FRAME_BODY_FRD = 12;
const octet obstacle_distance__MAV_DISTANCE_SENSOR_LASER = 0;
const octet obstacle_distance__MAV_DISTANCE_SENSOR_ULTRASOUND = 1;
const octet obstacle_distance__MAV_DISTANCE_SENSOR_INFRARED = 2;
const octet obstacle_distance__MAV_DISTANCE_SENSOR_RADAR = 3;

typedef unsigned short obstacle_distance__unsigned_short_array_72[72];

struct obstacle_distance
{
    unsigned long long timestamp_;
    octet frame_;
    octet sensor_type_;
    obstacle_distance__unsigned_short_array_72 distances;
    float increment_;
    unsigned short min_distance_;
    unsigned short max_distance_;
    float angle_offset_;

}; // struct obstacle_distance

#pragma keylist obstacle_distance

#endif  // __obstacle_distance__idl__
