
#ifndef __optical_flow__idl__
#define __optical_flow__idl__



const octet optical_flow__MODE_UNKNOWN = 0;
const octet optical_flow__MODE_BRIGHT = 1;
const octet optical_flow__MODE_LOWLIGHT = 2;
const octet optical_flow__MODE_SUPER_LOWLIGHT = 3;


struct optical_flow
{
    unsigned long long timestamp_;
    octet sensor_id_;
    float pixel_flow_x_integral_;
    float pixel_flow_y_integral_;
    float gyro_x_rate_integral_;
    float gyro_y_rate_integral_;
    float gyro_z_rate_integral_;
    float ground_distance_m_;
    unsigned long integration_timespan_;
    unsigned long time_since_last_sonar_update_;
    unsigned short frame_count_since_last_readout_;
    short gyro_temperature_;
    octet quality_;
    float max_flow_rate_;
    float min_ground_distance_;
    float max_ground_distance_;
    octet mode_;

}; // struct optical_flow

#pragma keylist optical_flow

#endif  // __optical_flow__idl__
