
#ifndef __sensor_selection__idl__
#define __sensor_selection__idl__





struct sensor_selection
{
    unsigned long long timestamp_;
    unsigned long accel_device_id_;
    unsigned long gyro_device_id_;

}; // struct sensor_selection

#pragma keylist sensor_selection

#endif  // __sensor_selection__idl__
