
#ifndef __vehicle_local_position_setpoint__idl__
#define __vehicle_local_position_setpoint__idl__




typedef float vehicle_local_position_setpoint__float_array_3[3];

struct vehicle_local_position_setpoint
{
    unsigned long long timestamp_;
    float x_;
    float y_;
    float z_;
    float yaw_;
    float yawspeed_;
    float vx_;
    float vy_;
    float vz_;
    vehicle_local_position_setpoint__float_array_3 acceleration;
    vehicle_local_position_setpoint__float_array_3 jerk;
    vehicle_local_position_setpoint__float_array_3 thrust;

}; // struct vehicle_local_position_setpoint

#pragma keylist vehicle_local_position_setpoint

#endif  // __vehicle_local_position_setpoint__idl__
