
#ifndef __vehicle_status__idl__
#define __vehicle_status__idl__



const octet vehicle_status__ARMING_STATE_INIT = 0;
const octet vehicle_status__ARMING_STATE_STANDBY = 1;
const octet vehicle_status__ARMING_STATE_ARMED = 2;
const octet vehicle_status__ARMING_STATE_STANDBY_ERROR = 3;
const octet vehicle_status__ARMING_STATE_SHUTDOWN = 4;
const octet vehicle_status__ARMING_STATE_IN_AIR_RESTORE = 5;
const octet vehicle_status__ARMING_STATE_MAX = 6;
const octet vehicle_status__FAILURE_NONE = 0;
const octet vehicle_status__FAILURE_ROLL = 1;
const octet vehicle_status__FAILURE_PITCH = 2;
const octet vehicle_status__FAILURE_ALT = 4;
const octet vehicle_status__FAILURE_EXT = 8;
const octet vehicle_status__FAILURE_ARM_ESC = 16;
const octet vehicle_status__HIL_STATE_OFF = 0;
const octet vehicle_status__HIL_STATE_ON = 1;
const octet vehicle_status__NAVIGATION_STATE_MANUAL = 0;
const octet vehicle_status__NAVIGATION_STATE_ALTCTL = 1;
const octet vehicle_status__NAVIGATION_STATE_POSCTL = 2;
const octet vehicle_status__NAVIGATION_STATE_AUTO_MISSION = 3;
const octet vehicle_status__NAVIGATION_STATE_AUTO_LOITER = 4;
const octet vehicle_status__NAVIGATION_STATE_AUTO_RTL = 5;
const octet vehicle_status__NAVIGATION_STATE_AUTO_LANDENGFAIL = 8;
const octet vehicle_status__NAVIGATION_STATE_AUTO_LANDGPSFAIL = 9;
const octet vehicle_status__NAVIGATION_STATE_ACRO = 10;
const octet vehicle_status__NAVIGATION_STATE_UNUSED = 11;
const octet vehicle_status__NAVIGATION_STATE_DESCEND = 12;
const octet vehicle_status__NAVIGATION_STATE_TERMINATION = 13;
const octet vehicle_status__NAVIGATION_STATE_OFFBOARD = 14;
const octet vehicle_status__NAVIGATION_STATE_STAB = 15;
const octet vehicle_status__NAVIGATION_STATE_UNUSED2 = 16;
const octet vehicle_status__NAVIGATION_STATE_AUTO_TAKEOFF = 17;
const octet vehicle_status__NAVIGATION_STATE_AUTO_LAND = 18;
const octet vehicle_status__NAVIGATION_STATE_AUTO_FOLLOW_TARGET = 19;
const octet vehicle_status__NAVIGATION_STATE_AUTO_PRECLAND = 20;
const octet vehicle_status__NAVIGATION_STATE_ORBIT = 21;
const octet vehicle_status__NAVIGATION_STATE_MAX = 22;
const octet vehicle_status__RC_IN_MODE_DEFAULT = 0;
const octet vehicle_status__RC_IN_MODE_OFF = 1;
const octet vehicle_status__RC_IN_MODE_GENERATED = 2;
const octet vehicle_status__VEHICLE_TYPE_UNKNOWN = 0;
const octet vehicle_status__VEHICLE_TYPE_ROTARY_WING = 1;
const octet vehicle_status__VEHICLE_TYPE_FIXED_WING = 2;
const octet vehicle_status__VEHICLE_TYPE_ROVER = 3;
const octet vehicle_status__VEHICLE_TYPE_AIRSHIP = 4;
const octet vehicle_status__ARM_DISARM_REASON_TRANSITION_TO_STANDBY = 0;
const octet vehicle_status__ARM_DISARM_REASON_RC_STICK = 1;
const octet vehicle_status__ARM_DISARM_REASON_RC_SWITCH = 2;
const octet vehicle_status__ARM_DISARM_REASON_COMMAND_INTERNAL = 3;
const octet vehicle_status__ARM_DISARM_REASON_COMMAND_EXTERNAL = 4;
const octet vehicle_status__ARM_DISARM_REASON_MISSION_START = 5;
const octet vehicle_status__ARM_DISARM_REASON_SAFETY_BUTTON = 6;
const octet vehicle_status__ARM_DISARM_REASON_AUTO_DISARM_LAND = 7;
const octet vehicle_status__ARM_DISARM_REASON_AUTO_DISARM_PREFLIGHT = 8;
const octet vehicle_status__ARM_DISARM_REASON_KILL_SWITCH = 9;
const octet vehicle_status__ARM_DISARM_REASON_LOCKDOWN = 10;
const octet vehicle_status__ARM_DISARM_REASON_FAILURE_DETECTOR = 11;
const octet vehicle_status__ARM_DISARM_REASON_SHUTDOWN = 12;
const octet vehicle_status__ARM_DISARM_REASON_UNIT_TEST = 13;


struct vehicle_status
{
    unsigned long long timestamp_;
    octet nav_state_;
    unsigned long long nav_state_timestamp_;
    octet arming_state_;
    octet hil_state_;
    boolean failsafe_;
    unsigned long long failsafe_timestamp_;
    octet system_type_;
    octet system_id_;
    octet component_id_;
    octet vehicle_type_;
    boolean is_vtol_;
    boolean is_vtol_tailsitter_;
    boolean vtol_fw_permanent_stab_;
    boolean in_transition_mode_;
    boolean in_transition_to_fw_;
    boolean rc_signal_lost_;
    octet rc_input_mode_;
    boolean data_link_lost_;
    octet data_link_lost_counter_;
    boolean high_latency_data_link_lost_;
    boolean engine_failure_;
    boolean mission_failure_;
    boolean geofence_violated_;
    octet failure_detector_status_;
    unsigned long onboard_control_sensors_present_;
    unsigned long onboard_control_sensors_enabled_;
    unsigned long onboard_control_sensors_health_;
    octet latest_arming_reason_;
    octet latest_disarming_reason_;
    unsigned long long armed_time_;
    unsigned long long takeoff_time_;

}; // struct vehicle_status

#pragma keylist vehicle_status

#endif  // __vehicle_status__idl__
