
#ifndef __vehicle_mocap_odometry__idl__
#define __vehicle_mocap_odometry__idl__



const octet vehicle_mocap_odometry__POSE_FRAME_UNKNOWN = 0;
const octet vehicle_mocap_odometry__POSE_FRAME_NED = 1;
const octet vehicle_mocap_odometry__POSE_FRAME_FRD = 2;
const octet vehicle_mocap_odometry__VELOCITY_FRAME_UNKNOWN = 0;
const octet vehicle_mocap_odometry__VELOCITY_FRAME_NED = 1;
const octet vehicle_mocap_odometry__VELOCITY_FRAME_FRD = 2;
const octet vehicle_mocap_odometry__VELOCITY_FRAME_BODY_FRD = 3;

typedef float vehicle_mocap_odometry__float_array_4[4];
typedef float vehicle_mocap_odometry__float_array_3[3];

struct vehicle_mocap_odometry
{
    unsigned long long timestamp_;
    unsigned long long timestamp_sample_;
    octet pose_frame_;
    vehicle_mocap_odometry__float_array_3 position;
    vehicle_mocap_odometry__float_array_4 q;
    octet velocity_frame_;
    vehicle_mocap_odometry__float_array_3 velocity;
    vehicle_mocap_odometry__float_array_3 angular_velocity;
    vehicle_mocap_odometry__float_array_3 position_variance;
    vehicle_mocap_odometry__float_array_3 orientation_variance;
    vehicle_mocap_odometry__float_array_3 velocity_variance;
    octet reset_counter_;
    octet quality_;

}; // struct vehicle_mocap_odometry

#pragma keylist vehicle_mocap_odometry

#endif  // __vehicle_mocap_odometry__idl__
