
#ifndef __wind_estimate__idl__
#define __wind_estimate__idl__





struct wind_estimate
{
    unsigned long long timestamp_;
    float windspeed_north_;
    float windspeed_east_;
    float variance_north_;
    float variance_east_;
    float tas_innov_;
    float tas_innov_var_;
    float tas_scale_;
    float beta_innov_;
    float beta_innov_var_;

}; // struct wind_estimate

#pragma keylist wind_estimate

#endif  // __wind_estimate__idl__
