// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file sensor_selection.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _SENSOR_SELECTION_H_
#define _SENSOR_SELECTION_H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(sensor_selection_SOURCE)
#define sensor_selection_DllAPI __declspec( dllexport )
#else
#define sensor_selection_DllAPI __declspec( dllimport )
#endif // sensor_selection_SOURCE
#else
#define sensor_selection_DllAPI
#endif
#else
#define sensor_selection_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}


/*!
 * @brief This class represents the structure sensor_selection defined by the user in the IDL file.
 * @ingroup SENSOR_SELECTION
 */
class sensor_selection
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport sensor_selection();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~sensor_selection();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object sensor_selection that will be copied.
     */
    eProsima_user_DllExport sensor_selection(const sensor_selection &x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object sensor_selection that will be copied.
     */
    eProsima_user_DllExport sensor_selection(sensor_selection &&x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object sensor_selection that will be copied.
     */
    eProsima_user_DllExport sensor_selection& operator=(const sensor_selection &x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object sensor_selection that will be copied.
     */
    eProsima_user_DllExport sensor_selection& operator=(sensor_selection &&x);

    /*!
     * @brief This function sets a value in member timestamp_
     * @param _timestamp_ New value for member timestamp_
     */
    eProsima_user_DllExport void timestamp_(uint64_t _timestamp_);

    /*!
     * @brief This function returns the value of member timestamp_
     * @return Value of member timestamp_
     */
    eProsima_user_DllExport uint64_t timestamp_() const;

    /*!
     * @brief This function returns a reference to member timestamp_
     * @return Reference to member timestamp_
     */
    eProsima_user_DllExport uint64_t& timestamp_();

    /*!
     * @brief This function sets a value in member accel_device_id_
     * @param _accel_device_id_ New value for member accel_device_id_
     */
    eProsima_user_DllExport void accel_device_id_(uint32_t _accel_device_id_);

    /*!
     * @brief This function returns the value of member accel_device_id_
     * @return Value of member accel_device_id_
     */
    eProsima_user_DllExport uint32_t accel_device_id_() const;

    /*!
     * @brief This function returns a reference to member accel_device_id_
     * @return Reference to member accel_device_id_
     */
    eProsima_user_DllExport uint32_t& accel_device_id_();

    /*!
     * @brief This function sets a value in member gyro_device_id_
     * @param _gyro_device_id_ New value for member gyro_device_id_
     */
    eProsima_user_DllExport void gyro_device_id_(uint32_t _gyro_device_id_);

    /*!
     * @brief This function returns the value of member gyro_device_id_
     * @return Value of member gyro_device_id_
     */
    eProsima_user_DllExport uint32_t gyro_device_id_() const;

    /*!
     * @brief This function returns a reference to member gyro_device_id_
     * @return Reference to member gyro_device_id_
     */
    eProsima_user_DllExport uint32_t& gyro_device_id_();

    /*!
     * @brief This function sets a value in member mag_device_id_
     * @param _mag_device_id_ New value for member mag_device_id_
     */
    eProsima_user_DllExport void mag_device_id_(uint32_t _mag_device_id_);

    /*!
     * @brief This function returns the value of member mag_device_id_
     * @return Value of member mag_device_id_
     */
    eProsima_user_DllExport uint32_t mag_device_id_() const;

    /*!
     * @brief This function returns a reference to member mag_device_id_
     * @return Reference to member mag_device_id_
     */
    eProsima_user_DllExport uint32_t& mag_device_id_();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(const sensor_selection& data, size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

private:
    uint64_t m_timestamp_;
    uint32_t m_accel_device_id_;
    uint32_t m_gyro_device_id_;
    uint32_t m_mag_device_id_;
};

#endif // _SENSOR_SELECTION_H_