// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file vehicle_rates_setpoint.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _VEHICLE_RATES_SETPOINT_H_
#define _VEHICLE_RATES_SETPOINT_H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(vehicle_rates_setpoint_SOURCE)
#define vehicle_rates_setpoint_DllAPI __declspec( dllexport )
#else
#define vehicle_rates_setpoint_DllAPI __declspec( dllimport )
#endif // vehicle_rates_setpoint_SOURCE
#else
#define vehicle_rates_setpoint_DllAPI
#endif
#else
#define vehicle_rates_setpoint_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}


typedef std::array<float, 3> vehicle_rates_setpoint__float_array_3;
/*!
 * @brief This class represents the structure vehicle_rates_setpoint defined by the user in the IDL file.
 * @ingroup VEHICLE_RATES_SETPOINT
 */
class vehicle_rates_setpoint
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport vehicle_rates_setpoint();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~vehicle_rates_setpoint();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object vehicle_rates_setpoint that will be copied.
     */
    eProsima_user_DllExport vehicle_rates_setpoint(const vehicle_rates_setpoint &x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object vehicle_rates_setpoint that will be copied.
     */
    eProsima_user_DllExport vehicle_rates_setpoint(vehicle_rates_setpoint &&x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object vehicle_rates_setpoint that will be copied.
     */
    eProsima_user_DllExport vehicle_rates_setpoint& operator=(const vehicle_rates_setpoint &x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object vehicle_rates_setpoint that will be copied.
     */
    eProsima_user_DllExport vehicle_rates_setpoint& operator=(vehicle_rates_setpoint &&x);

    /*!
     * @brief This function sets a value in member timestamp_
     * @param _timestamp_ New value for member timestamp_
     */
    eProsima_user_DllExport void timestamp_(uint64_t _timestamp_);

    /*!
     * @brief This function returns the value of member timestamp_
     * @return Value of member timestamp_
     */
    eProsima_user_DllExport uint64_t timestamp_() const;

    /*!
     * @brief This function returns a reference to member timestamp_
     * @return Reference to member timestamp_
     */
    eProsima_user_DllExport uint64_t& timestamp_();

    /*!
     * @brief This function sets a value in member roll_
     * @param _roll_ New value for member roll_
     */
    eProsima_user_DllExport void roll_(float _roll_);

    /*!
     * @brief This function returns the value of member roll_
     * @return Value of member roll_
     */
    eProsima_user_DllExport float roll_() const;

    /*!
     * @brief This function returns a reference to member roll_
     * @return Reference to member roll_
     */
    eProsima_user_DllExport float& roll_();

    /*!
     * @brief This function sets a value in member pitch_
     * @param _pitch_ New value for member pitch_
     */
    eProsima_user_DllExport void pitch_(float _pitch_);

    /*!
     * @brief This function returns the value of member pitch_
     * @return Value of member pitch_
     */
    eProsima_user_DllExport float pitch_() const;

    /*!
     * @brief This function returns a reference to member pitch_
     * @return Reference to member pitch_
     */
    eProsima_user_DllExport float& pitch_();

    /*!
     * @brief This function sets a value in member yaw_
     * @param _yaw_ New value for member yaw_
     */
    eProsima_user_DllExport void yaw_(float _yaw_);

    /*!
     * @brief This function returns the value of member yaw_
     * @return Value of member yaw_
     */
    eProsima_user_DllExport float yaw_() const;

    /*!
     * @brief This function returns a reference to member yaw_
     * @return Reference to member yaw_
     */
    eProsima_user_DllExport float& yaw_();

    /*!
     * @brief This function copies the value in member thrust_body
     * @param _thrust_body New value to be copied in member thrust_body
     */
    eProsima_user_DllExport void thrust_body(const vehicle_rates_setpoint__float_array_3 &_thrust_body);

    /*!
     * @brief This function moves the value in member thrust_body
     * @param _thrust_body New value to be moved in member thrust_body
     */
    eProsima_user_DllExport void thrust_body(vehicle_rates_setpoint__float_array_3 &&_thrust_body);

    /*!
     * @brief This function returns a constant reference to member thrust_body
     * @return Constant reference to member thrust_body
     */
    eProsima_user_DllExport const vehicle_rates_setpoint__float_array_3& thrust_body() const;

    /*!
     * @brief This function returns a reference to member thrust_body
     * @return Reference to member thrust_body
     */
    eProsima_user_DllExport vehicle_rates_setpoint__float_array_3& thrust_body();

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(const vehicle_rates_setpoint& data, size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

private:
    uint64_t m_timestamp_;
    float m_roll_;
    float m_pitch_;
    float m_yaw_;
    vehicle_rates_setpoint__float_array_3 m_thrust_body;
};

#endif // _VEHICLE_RATES_SETPOINT_H_